### PR TITLE
Added support for loading JSON/YAML files for topology (with .yaml, yml and .json extensions)

### PR DESCRIPTION
**Pull request by ashutshkumr**
Fixes https://github.com/google/kne/issues/93.

File formats are detected based on extensions `.yaml`, `.yml` and `.json`. If no match is found, files are assumed to be .pb.txt (i.e. no check for extension when loading .pb.txt, as was the case before).

### CODE REVIEW

**Comment by marcushines** [comment]
Why exactly are wanting to add support for these formats?

**Comment by marcushines** [comment]
Also assuming we want add these formats - there should be unittests for these as well

**Comment by ashutshkumr** [comment]
@marcushines mentioned the reasons to issue https://github.com/google/kne/issues/93.

We may hold this if reasons are not strong enough. Otherwise, I'll look into fixing the coverage (probably need to add some negative cases).

**Comment by hellt** [comment]
I'd like to see yaml/json support
writing prototext is a pain (at least for me)

**Comment by ashutshkumr** [comment]
Update on coverage. I checked locally on why `coveralls` shows decrease in coverage but not sure what's up.
So executed following locally, found out `Load` was not unit tested at all in main.

```
go test -cover -coverprofile cover.out ./... && go tool cover -func cover.out | grep Load
```

- in main: Load is not covered (no tests)
- in yaml-support (initial push): 76.5% covered
- in yaml-support (after adding negative TCs): 84.6% covered

**Comment by ashutshkumr** [comment]
As discussed, also removed support for loading `.json`.

**Comment by marcushines** [comment]
can you fix the merge conflicts for this PR so we can close this out?

**Comment by ashutshkumr** [comment]
resolved build failure after merge, awaiting CI results.

**Review by marcushines — DISMISSED** [review]
you need to fix the last merge conflict but lgtm

**Comment by ashutshkumr** [comment]
@marcushines fixed latest merge conflict, but it seems to have turned your previous review stale. Could you please re-approve if all looks good ?

**Review by alexmasi — APPROVED** [review]

**Comment by ashutshkumr** [comment]
I have fixed newly introduced conflicts. Would request if this PR is merged before other pending PRs to avoid any further conflicts (this was the third one).

**Review by marcushines — APPROVED** [review]

**Pull request merged**
