### PR TITLE
Add link for cPTX from github.

### PR DESCRIPTION
**Pull request by kmo7**
* This allows cPTX topo deployment from KNE's github repo.

* Added copyright string for cPTX per Juniper Legal team request.

### CODE REVIEW

**Comment by kmo7** [comment]
Hi Marcus, please review this at your convenience. Thanks, Kaveh

**Comment by marcushines** [comment]
just FYI - had to ask internally if there was any reason we could care about you adding a juniper copyright into this file.
I think the answer is we don't care but just wanted clarification before merging

**Comment by kmo7** [comment]
Ack. Marcus, guessed that was the reason for waiting to merge. This was a request from our legal team, which as you know has also approved the google CLA.
Please let me know when your legal team decides.  Thanks, Kaveh



Juniper Business Use Only

**Review by marcushines — APPROVED** [review]
Checked with legal and adding a copyright here is fine

**Pull request merged**
